# .github/workflows/deploy.yml

name: Deploy Python App to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 1. Checkout Code
      uses: actions/checkout@v4

    - name: 2. Setup SSH Key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.EC2_PRIVATE_KEY }}

    - name: 3. Deploy to EC2 and Restart App
      run: |
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

        # === FIX: CREATE DEPLOYMENT DIRECTORY ===
        # Create the deployment directory on the server if it doesn't exist.
        # The 'mkdir -p' command creates parent directories as needed and doesn't fail if the directory already exists.
        ssh ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "mkdir -p ${{ secrets.DEPLOY_PATH }}"

        # Now that the directory is guaranteed to exist, run rsync.
        rsync -avz --exclude '.git' --exclude '.github' --exclude 'venv' . ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:${{ secrets.DEPLOY_PATH }}

        # The rest of the script remains the same.
        ssh ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} << 'EOF'
          set -e # Exit immediately if a command fails

          cd ${{ secrets.DEPLOY_PATH }}

          if [ ! -d "venv" ]; then
            echo "Creating Python virtual environment..."
            python3 -m venv venv
          fi

          echo "Activating virtual environment and installing dependencies..."
          ./venv/bin/pip install -r requirements.txt

          echo "Stopping old application process..."
          pkill -f "${{ secrets.DEPLOY_PATH }}/venv/bin/python app.py" || true

          echo "Starting new application process..."
          nohup ./venv/bin/python app.py > output.log 2>&1 &

          echo "Deployment successful!"
        EOF